#!/bin/bash

#23FEB2025 last edit KM4ACK

export MYPATH="$(cd "$(dirname "$0")" && pwd)"

#dependencies
#voacap
sudo apt install build-essential gfortran -y
cd ${HOME}/Downloads
wget https://github.com/jawatson/voacapl/archive/refs/tags/v.0.7.6.zip
unzip v.0.7.6.zip
cd voacapl-v.0.7.6
./configure
make
if [ -z $SUDO_ASKPASS ]; then
  echo "building voacap"
  echo "enter sudo password if asked"
  sudo make install
else
  sudo -A make install
fi
makeitshfbc

#wwl
cd ${HOME}/Downloads
wget http://db.net/downloads/wwl+db-1.3.tgz
tar -xvzf wwl+db-1.3.tgz
cd wwl+db-1.3
make
if [ -z $SUDO_ASKPASS ]; then
  echo "installing wwl"
  echo "enter sudo password if asked"
  sudo make install
else
  sudo -A make install
fi


if [ -d $HOME/patmenu2 ]; then
  #remove old desktop file
  if [ -f /usr/local/share/applications/patmenu.desktop ]; then
    if [ -z $SUDO_ASKPASS ]; then
      echo "removing old menu shortcuts"
      echo "enter sudo password if asked"
      sudo rm /usr/local/share/applications/patmenu.desktop
    else
      sudo -A rm /usr/local/share/applications/patmenu.desktop
    fi
  fi
    if [ -f /usr/local/share/applications/patmenu2.desktop ]; then
      if [ -z $SUDO_ASKPASS ]; then
        echo "removing old menu shortcuts"
        echo "enter sudo password if asked"
        sudo rm /usr/local/share/applications/patmenu2.desktop
      else
        sudo -A rm /usr/local/share/applications/patmenu2.desktop
      fi
  fi
fi

#make files executable
chmod +x ${MYPATH}/patmenu
chmod +x ${MYPATH}/bin/getgrid ${MYPATH}/bin/pat-contacts ${MYPATH}/bin/getardoplist ${MYPATH}/bin/stats ${MYPATH}/bin/.getardoplist-cron
chmod +x ${MYPATH}/bin/catelog/*
chmod +x ${MYPATH}/bin/config/*
chmod +x ${MYPATH}/bin/find-gateways/*
chmod +x ${MYPATH}/bin/manage_mail/*
chmod +x ${MYPATH}/bin/modems/*
chmod +x ${MYPATH}/bin/pat_admin/*
chmod +x ${MYPATH}/bin/pos/*
chmod +x ${MYPATH}/bin/sms/add-carrier ${MYPATH}/bin/sms/current-carriers \
chmod +x ${MYPATH}/bin/voacap/rel.ph ${MYPATH}/bin/voacap/voa.sh ${MYPATH}/bin/voacap/voacap
${MYPATH}/bin/sms/manage-sms ${MYPATH}/bin/sms/remove-carrier ${MYPATH}/bin/sms/winlink2sms


#create shortcut
cat <<EOF >${MYPATH}/data/patmenu.desktop 
[Desktop Entry]
Name=Pat Menu
GenericName=Amateur Radio Digital Modem
Comment=Amateur Radio Sound Card Communications
Exec=${MYPATH}/patmenu
Icon=${MYPATH}/pmlogo.png
Terminal=false
Type=Application
Categories=Network;HamRadio;
EOF

if [ -z $SUDO_ASKPASS ]; then
  echo "creating menu shortcut for patmenu"
  echo "enter sudo password if asked"
  sudo cp ${MYPATH}/data/patmenu.desktop /usr/local/share/applications/
else
  sudo -A cp ${MYPATH}/data/patmenu.desktop /usr/local/share/applications/
fi




